### ISSUE TITLE
Challenge 4 debug issue

### ISSUE THREAD

**Issue by cheahengsoon** [tanloiit2010/BotFramework-Tutorial#1]
When I run the application in Bot Framework Emulator ,
It's display the error
"request to http://localhost:3978/api/messages failed, reason: connect ECONNREFUSED 127.0.0.1:3978"

**Comment by tanloiit2010** [comment]
Hi @cheahengsoon ,

I checked and Challenge 4 work ok in my machine at the time being.
Could you provide more info about this case? you run in Window or Mac?

Thanks,
Loi Le

**Comment by cheahengsoon** [comment]
> Hi @cheahengsoon ,
> 
> I checked and Challenge 4 work ok in my machine at the time being.
> Could you provide more info about this case? you run in Window or Mac?
> 
> Thanks,
> Loi Le

Hi Loi Le,

I run in Windows. 
myfirstbot.bot only run the challenge3 bot, when I enter "book room,please" , the bot reply "I did not undertand what you said to me".

Thank you,
Eng Soon

**Comment by cheahengsoon** [comment]
@tanloiit2010 now can already . due to the emulator issue, quick slow respond.
